package com.andreutp.centromasajes.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.time.LocalDateTime;
import java.util.Collections;

import org.junit.jupiter.api.Test;

class PaymentModelTest {

    @Test
    void constructorAndGettersSetters() {
        PaymentModel payment = new PaymentModel();
        payment.setId(5L);
        payment.setAmount(123.45);
        LocalDateTime now = LocalDateTime.now();
        payment.setPaymentDate(now);
        payment.setMethod("CASH");
        payment.setCoveredBySubscription(true);
        payment.setStatus(PaymentModel.Status.PAID);

        assertEquals(5L, payment.getId());
        assertEquals(123.45, payment.getAmount());
        assertEquals(now, payment.getPaymentDate());
        assertEquals("CASH", payment.getMethod());
        assertEquals(true, payment.getCoveredBySubscription());
        assertEquals(PaymentModel.Status.PAID, payment.getStatus());

        // builder and all args are generated by Lombok; verify builder works
        PaymentModel built = PaymentModel.builder()
                .id(10L)
                .amount(200.0)
                .method("CARD")
                .status(PaymentModel.Status.PENDING)
                .build();
        assertEquals(10L, built.getId());
        assertEquals("CARD", built.getMethod());
        assertEquals(PaymentModel.Status.PENDING, built.getStatus());
    }
}
